### ISSUE TITLE
Проверить ДЗ (покупки)

### ISSUE THREAD

**Issue by andruhanishe** [andruhanishe/Calc_of_costs#1]
@coursar, прошу проверить ДЗ

Не могу понять, почему сначала выполняются функции ниже цикла и только потом сам цикл и удаление из массива purchaises[]
https://github.com/andruhanishe/Calc_of_costs/blob/c5ad61dc232ab5e7c86b8883a07d4cb76e4365d9/src/js/app.js#L109-L140

**Comment by coursar** [comment]
А зачем вам onclick а parent? Вы же должны на click на removeEl реагировать.

Так получается, что при первом клике на removeEl, вы навешиваете обработчик на parent. И, видимо, он-то потом и начинает срабатывать.

Вам или через поиск родителей из removeEl нужно добраться до самого элемента, чтобы потом его вырезать, либо у removeEl устанавливать свойство, которое поможет не искать элемент.

Второй обработчки (`onclick`) выставлять не нужно.
